version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4321:4321'
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
      # Variables de entorno para Clerk (configúralas en Coolify)
      - PUBLIC_CLERK_PUBLISHABLE_KEY=${PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      # Variables de entorno para base de datos SQLite
      - DATABASE_URL=file:./data/production.db
      # Variables adicionales que puedas necesitar
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    volumes:
      - sqlite_data:/app/data
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local
